# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
rssFullContent = true
favicon = "img/favicon.png"

SortBy = "default"

[footer]
since = 2023
customText = "Powered by Hugo "

[dateFormat]
published = ":date_full"
lastUpdated = ":date_full"

[sidebar]
emoji = ""
subtitle = "自由软件爱好者。"
avatar = "img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
homepage = [
  { type = "search" },
  { type = "archives", params = { limit = 5 } },
  { type = "categories", params = { limit = 10 } },
  { type = "tag-cloud", params = { limit = 10 } },
]
page = [{ type = "toc" }]

[opengraph.twitter]
site = "@k49ur473"
card = "summary_large_image"

[colorScheme]
toggle = true
default = "auto"

[comments]
enabled = false
provider = "disqus"
